name: Tests

on:
  push:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version:
          - '2.7'
          - '3.6'
          - '3.7'
          - '3.8'
          - '3.9'
          - '3.10'

    runs-on: ${{ matrix.os }}

    name: ${{ matrix.os }}, Python ${{ matrix.python-version }}

    steps:
      - uses: actions/checkout@v2
      - run: pip install pytest coverage
      - run: coverage run --source pylocalstorage --branch -m pytest -v
      - run: coverage report -m
      - run: >-
          curl -X PUT -H "Content-Type: application/json" -d '{"schemaVersion":1,"label":"coverage","message":"85%","color":"yellow"}' https://jsonblob.com/api/jsonBlob/1002315458195767296
