name: Tests

on:
  push:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version:
          - '2.7'
          - '3.6'
          - '3.7'
          - '3.8'
          - '3.9'
          - '3.10'

    runs-on: ${{ matrix.os }}

    name: ${{ matrix.os }}, Python ${{ matrix.python-version }}

    steps:
      - uses: actions/checkout@v2
      - run: |
          pip install pytest coverage
          coverage run --source pylocalstorage --branch -m pytest -v
          # COV=$(coverage report -m | grep 'TOTAL' | awk '{print $NF}')
          # curl -X PUT -H "Content-Type: application/json" -d '{"schemaVersion":1,"label":"coverage","message":"'$COV'","color":"yellow"}' https://jsonblob.com/api/jsonBlob/1002315458195767296
          coverage report -m | findstr /c:"TOTAL" >temp.txt
          python -c "with open('temp.txt') as f: print(f.read().split(' ')[-1])" >temp2.txt
          set /p COV= <temp2.txt
          DEL /q temp.txt
          DEL /q temp2.txt
          curl -X PUT -H "Content-Type: application/json" -d "{'schemaVersion':1,'label':'coverage','message':'%COV%','color':'yellow'}" https://jsonblob.com/api/jsonBlob/1002315458195767296
