name: Tests

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - run: pip install pytest
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: pytest
