name: Tests

on: push

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version:
          - '2.7'
          - '3.6'
          - '3.7'
          - '3.8'
          - '3.9'
          - '3.10'

    runs-on: ${{ matrix.os }}

    name: ${{ matrix.os }}, Python ${{ matrix.python-version }}

    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
      - run: pip install pytest
      - run: pytest tests
