name: Tests

on:
  push:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version:
          - '2.7'
          - '3.6'
          - '3.7'
          - '3.8'
          - '3.9'
          - '3.10'

    runs-on: ${{ matrix.os }}

    name: ${{ matrix.os }}, Python ${{ matrix.python-version }}

    steps:
      - uses: actions/checkout@v2
      - run: |
          pip install pytest coverage
          coverage run --source pylocalstorage --branch -m pytest -v
          coverage report -m
      - if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          # coverage report -m | findstr /c:"TOTAL"
          COV=$(coverage report -m | grep 'TOTAL' | awk '{print $NF}')
          curl -X PUT -H "Content-Type: application/json" -d '{"schemaVersion":1,"label":"coverage","message":"'$COV'","color":"yellow","namedLogo":"jest"}' https://jsonblob.com/api/jsonBlob/1002315458195767296
